# Generated by Django 5.1.15 on 2026-07-05 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="deposit_deducted",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rental",
            name="deposit_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="deposit_refunded",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rental",
            name="deposit_settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DepositSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "damage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount deducted from the deposit due to damage / loss.",
                        max_digits=10,
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount returned to the customer.",
                        max_digits=10,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="What happened? Visible to the customer."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="rentals.rental",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
