# Generated by Django 6.1 on 2026-08-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catergory",
            new_name="Category",
        ),
    ]
