# Generated by Django 4.2.10 on 2026-01-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapist",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="therapists", to="core.service"
            ),
        ),
    ]
