# Generated by Django 4.2.10 on 2026-01-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_therapist_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapist",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="therapist_photos/"
            ),
        ),
    ]
