# Generated by Django 5.1.15 on 2026-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="booking_count",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="How many times this product has been booked. Drives the trending ranking.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Percent off the per-day price. 0 = no discount. Capped at 90.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_hot_deal",
            field=models.BooleanField(
                default=False,
                help_text="Surface this product in the Hot Deals / Trending section on the home page.",
            ),
        ),
    ]
